baseURL = 'http://localhost:1313'
theme = "based"
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.fr]
    languageCode = 'fr'
    languageDirection = 'ltr'
    languageName = 'Français'
    title = 'N3m0'
  [languages.en]
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'N3m0'
[params]
  [params.author]
    email = 'n3m0@bbc.fr'
    name = 'N3m0'
[taxonomies]
  category = 'categories'
  tag = 'tags'
  theme = 'themes'
[outputs]
  home = ['html', 'rss']
  section = ['html']
  taxonomy = ['html']
  term = ['html']
[markup.goldmark.renderer]
  unsafe = true
